# Setting

In [ ]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np

# Get jeju hotel info
- hotel code, hotel name, location info

### 제주 호텔 불러오는 함수

In [ ]:
# def 
def hotel_info(txt_url):
  global hotel_info_df
  # 호텔 url, name을 담기 위한 리스트 생성
  hotel_code = []
  hotel_name = []
  hotel_location = []

  # 반복문을 통해 호텔 url, name 담기
  txt = pd.read_table(txt_url)
  txt = txt.to_string() #dataframe을 string으로 변환
  hotel_info = txt.split("href=") # href 뒤에 호텔별 url 주소가 나오므로 먼저 'href=' 기준으로 split

  for i in range(1, len(hotel_info)): # 0번째는 사용할 필요 없으므로 1번째부터
    # 호텔 code
    url = hotel_info[i].split()[0].replace('"', "") # 필요없는 '"' 부분 제거
    hotel_code.append(url.split('hotel/')[1])

    # 호텔명
    name = hotel_info[i].split("title=") # 'title=' 뒤에 호텔명 나오므로 split
    name = name[1].split(">")[0].replace('"', "") # '>'까지 호텔명 받고 나머지 제거([0]) 후, '"' 부분 제거
    hotel_name.append(name)

  for i in range(0, len(hotel_name)):
    hotel_name[i] = hotel_name[i].replace(" class=common_clearfix__M6urU", "") # hotel_name 중에 일부 문자열이 생성되므로 삭제 

  hotel_info_df = pd.DataFrame(x for x in zip(hotel_code, hotel_name)) # 두가지 list 엮어서 dataframe화
  hotel_info_df.columns = ['hotel_code', 'hotel_name']
  return hotel_info_df

### 2-3. 확인

In [ ]:
# 호텔 정보 txt 가져오기
txt_url = '/content/drive/MyDrive/Codepresso/TeamProject/data/Seoul/seoul_review.txt' # 21.08.07 기준 제주 호텔 중 리뷰가 200개 이상인 호텔 관련 html 모음


hotel_info(txt_url) # 총 30개

    hotel_code                      hotel_name
0      3001395                        신라스테이 역삼
1      3001615                          카파스 호텔
2      3000769                     노보텔 앰배서더 강남
3      3001437                호텔 더 디자이너스 리즈 강남
4      3009050                        신라스테이 서초
5   1000105844                        신라스테이 삼성
6      3000742                 이비스 스타일 앰배서더 강남
7      3018171                      호텔 인 나인 강남
8      3011846                     L7 강남 바이 롯데
9   1000101062                신천(잠실새내) 호텔 더 캐슬
10     3014284                           호텔 뉴브
11     3000690                       라마다 서울 강남
12     3000865                       호텔 리베라 청담
13     3001516                         카푸치노 호텔
14     3000598                  베스트웨스턴 프리미어 강남
15     3000826                       나비 호텔레지던스
16     3006832                       호텔 엔트라 강남
17     3018171                      호텔 인 나인 강남
18    10039725  소피텔 앰배서더 서울 호텔 &amp; 서비스드 레지던스
19     3016868                      호텔 크레센도 서울
20     3008250                       잠실 딜라이트호텔
21     3000804                     임피리얼 팰리스 서울
22     3000638                     강남아르누보씨티 호텔
23     3000624                      역삼 아르누보 호텔
24  1000099895                     호스텔베네 롯데타워점
25  1000110881                          안테룸 서울
26     3002018                      글래드 라이브 강남
27     3001502                            호텔티롤
28     3001221                         롯데호텔 월드

In [ ]:
hotel_info_df

    hotel_code                      hotel_name
0      3001395                        신라스테이 역삼
1      3001615                          카파스 호텔
2      3000769                     노보텔 앰배서더 강남
3      3001437                호텔 더 디자이너스 리즈 강남
4      3009050                        신라스테이 서초
5   1000105844                        신라스테이 삼성
6      3000742                 이비스 스타일 앰배서더 강남
7      3018171                      호텔 인 나인 강남
8      3011846                     L7 강남 바이 롯데
9   1000101062                신천(잠실새내) 호텔 더 캐슬
10     3014284                           호텔 뉴브
11     3000690                       라마다 서울 강남
12     3000865                       호텔 리베라 청담
13     3001516                         카푸치노 호텔
14     3000598                  베스트웨스턴 프리미어 강남
15     3000826                       나비 호텔레지던스
16     3006832                       호텔 엔트라 강남
18    10039725  소피텔 앰배서더 서울 호텔 &amp; 서비스드 레지던스
19     3016868                      호텔 크레센도 서울
20     3008250                       잠실 딜라이트호텔
21     3000804                     임피리얼 팰리스 서울
22     3000638                     강남아르누보씨티 호텔
23     3000624                      역삼 아르누보 호텔
24  1000099895                     호스텔베네 롯데타워점
25  1000110881                          안테룸 서울
26     3002018                      글래드 라이브 강남
27     3001502                            호텔티롤
28     3001221                         롯데호텔 월드

In [ ]:
hotel_info_df.to_csv('/content/drive/MyDrive/Codepresso/TeamProject/data/Seoul/seoul_hotel_list.csv')